# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

variables:
- name: appServicePlanProjectName
  value: 'DurableFunctionAppService'
- name: durableFunctionAppProjectName
  value: 'DurableFunction'
- name: ARMSolutionPath
  value: 'Infrastructure/DurableFunctions'
- name: appName
  value:'DurableFunctionCode1'

stages:
- stage: BuildArtifcates
  jobs:
  - template: /CI_CD/copy_arm.yml
    parameters: 
      armProjectName: ${{ variables.appServicePlanProjectName }}
      solutionPath: $(ARMSolutionPath)
  - template: /CI_CD/build-dotnet-core-app.yml
    parameters:
       solutionPath: $(ARMSolutionPath)
       appName: $(appName)
- stage: DeployApp
  jobs:
  - deployment: Deploy_ARM
    environment: DurableFunctionCode1_DEV
    strategy:
     runOnce:
      deploy:
       steps:
       - download: none
       - task: DownloadBuildArtifacts@0
         inputs:
          artifactName: 'drop'
          buildType: 'current'
          downloadType: 'single'
          downloadPath: '$(System.ArtifactsDirectory)'
       - task: AzureResourceManagerTemplateDeployment@3
         displayName: 'ARM Template deployment: Resource Group scope'
         inputs:
          azureResourceManagerConnection: 'Visual Studio Enterprise Subscription(7893e52e-7759-4f17-9742-bd594ec7f695)'
          subscriptionId: '7893e52e-7759-4f17-9742-bd594ec7f695'
          resourceGroupName: 'rg-durablefunctions-dev-cus'
          location: 'Central US'
          csmFile: '$(build.artifactstagingdirectory)/drop/$(ARMSolutionPath)/$(appServicePlanProjectName)/durableplan.deploy.json'
          csmParametersFile: '$(build.artifactstagingdirectory)/drop/$(ARMSolutionPath)/$(appServicePlanProjectName)/durableplan.parameters.dev.json'

       - task: AzureResourceManagerTemplateDeployment@3
         displayName: 'ARM Template deployment: Resource Group scope'
         inputs:
          azureResourceManagerConnection: 'Visual Studio Enterprise Subscription(7893e52e-7759-4f17-9742-bd594ec7f695)'
          subscriptionId: '7893e52e-7759-4f17-9742-bd594ec7f695'
          resourceGroupName: 'rg-durablefunctions-dev-cus'
          location: 'Central US'
          csmFile: '$(build.artifactstagingdirectory)/drop/$(ARMSolutionPath)/$(durableFunctionAppProjectName)/durablefn.deploy.json'
          csmParametersFile: '$(build.artifactstagingdirectory)/drop/$(ARMSolutionPath)/$(durableFunctionAppProjectName)/durablefn.parameters.dev.json'
        - download: none
        - task: AzureResourceManagerTemplateDeployment@3
          displayName: 'ARM Template deployment: Resource Group scope'
          inputs:
            azureResourceManagerConnection: 'Visual Studio Enterprise Subscription(7893e52e-7759-4f17-9742-bd594ec7f695)'
            subscriptionId: '7893e52e-7759-4f17-9742-bd594ec7f695'
            resourceGroupName: 'rg-durablefunctions-dev-cus'
            location: 'Central US'
            csmFile: '$(Pipeline.Workspace)/drop/$(ARMSolutionPath)/$(appServicePlanProjectName)/durableplan.deploy.json'
            csmParametersFile: 'drop/Infrastructure/DurableFunctions/DurableFunctionAppService/durableplan.parameters.dev.json'
   - deployment: Deploy_ARM
    environment: DurableFunctionCode1_DEV
    strategy:
     runOnce:
      deploy:
       steps:
        - download: none
        - task: AzureRmWebAppDeployment@3
          inputs:
            azureSubscription: 'Visual Studio Enterprise Subscription(7893e52e-7759-4f17-9742-bd594ec7f695)'
            WebAppName: 'durablefunction-dev-fn-cus'
            Package: '${{ parameters.artifactPath }}'
            TakeAppOfflineFlag: true
            UseWebDeploy: true
            RemoveAdditionalFilesFlag: true
            ExcludeFilesFromAppDataFlag: true





