parameters:
  SolutionPath: ''
  ARMProjectName: ''
  DependsOn: []

  

jobs:
- job : Copy_${{ parameters.ARMProjectName }}_ARM
  dependsOn: ${{ parameters.DependsOn }}
  steps:
  - task: CopyFiles@2
    inputs:
      SourceFolder: '$(Build.SourcesDirectory)'
      Contents: '$(Build.SourcesDirectory)/${{ parameters.SolutionPath }}/${{ parameters.ARMProjectName }}/*.json'
      TargetFolder: '$(build.artifactstagingdirectory)'
  - task: PublishBuildArtifacts@1
    displayName: 'Publish Artifact: ARM'
    inputs:
        PathtoPublish: '$(build.artifactstagingdirectory)'
