jobs:
- job : PublishArtifacts
  steps:
  - task: PublishPipelineArtifact@1
    displayName: 'Publish Artifact: drop'
    inputs:
        PathtoPublish: '$(System.DefaultWorkingDirectory)'
        ArtifactName: 'drop'
