parameters:
  DependsOn: []

  

jobs:
- job : PublishArtifacts
  dependsOn: ${{ parameters.DependsOn }}
  steps:
  - task: PublishBuildArtifacts@1
    displayName: 'Publish Artifact: drop'
    inputs:
        PathtoPublish: '$(build.artifactstagingdirectory)'
        ArtifactName: 'drop'
